#!/bin/bash
# helper for creating data.
for i in $(seq 1 96) # 96 cores
do
        let front=i*22-22
        if [ $front -gt 2047 ]
        then
                break
        fi
        let back=i*22-1
        if [ $back -gt 2047 ]
        then
                let back=2047
        fi
        nohup bash create_pretraining_data_512_script $front $back >$front_$back 2>&1 &
        echo "$front-$back is running"
done
